import { Global, Module } from '@nestjs/common';

import { CommonLoggerService } from '../logger/logger.service.js';
import {
  CandidateDao,
  CandidateHasMediaDao,
  CandidateHasFeedbackDao,
  CurrencyDao,
  LeaveDao,
  MediaDao,
  PayrollPayslipDao,
  PolicyDao,
  PolicyHasMediaDao,
  UserDao,
  PayrollCompensationDao,
  PayrollDeductionDao,
  EmployeeDao,
  EmployeeFeedbackDao,
  EmployeeBgvFeedbackDao,
  EmployeeHasMediaDao,
  EmployeeLeaveCounterDao,
  OrganizationDao,
  OrganizationHasUserDao,
  OrganizationSettingDao,
  OrganizationHasDocumentDao,
  BranchDao,
  UserInBranchDao,
  UserInviteDao,
} from './dao/index.js';
import { PrismaService } from './prisma/prisma.service.js';
import { AuditService } from '../service/audit.service.js';
import { AuditActivityDao } from './dao/audit-activity.dao.js';
import { AuditActivityHasEntityDao } from './dao/audit-activity-has-entity.dao.js';
import { UserVerifyEmailDao } from './dao/user-verify-email.dao.js';
import { UserForgotPasswordDao } from './dao/user-forgot-password.dao.js';

@Global()
@Module({
  providers: [
    PrismaService,
    AuditService,
    CurrencyDao,
    UserDao,
    OrganizationDao,
    OrganizationHasUserDao,
    OrganizationSettingDao,
    OrganizationHasDocumentDao,
    BranchDao,
    UserInBranchDao,
    MediaDao,
    CandidateDao,
    CandidateHasMediaDao,
    CandidateHasFeedbackDao,
    EmployeeDao,
    EmployeeHasMediaDao,
    PayrollCompensationDao,
    PayrollDeductionDao,
    EmployeeFeedbackDao,
    EmployeeBgvFeedbackDao,
    LeaveDao,
    EmployeeLeaveCounterDao,
    PolicyDao,
    PolicyHasMediaDao,
    PayrollPayslipDao,
    CommonLoggerService,
    AuditActivityDao,
    AuditActivityHasEntityDao,
    UserForgotPasswordDao,
    UserVerifyEmailDao,
    UserInviteDao,
  ],
  exports: [
    PrismaService,
    AuditService,
    CurrencyDao,
    UserDao,
    OrganizationDao,
    OrganizationHasUserDao,
    OrganizationSettingDao,
    OrganizationHasDocumentDao,
    BranchDao,
    UserInBranchDao,
    MediaDao,
    CandidateDao,
    CandidateHasMediaDao,
    CandidateHasFeedbackDao,
    EmployeeDao,
    EmployeeHasMediaDao,
    PayrollCompensationDao,
    PayrollDeductionDao,
    EmployeeFeedbackDao,
    EmployeeBgvFeedbackDao,
    LeaveDao,
    EmployeeLeaveCounterDao,
    PolicyDao,
    PolicyHasMediaDao,
    PayrollPayslipDao,
    CommonLoggerService,
    AuditActivityDao,
    AuditActivityHasEntityDao,
    UserForgotPasswordDao,
    UserVerifyEmailDao,
    UserInviteDao,
  ],
})
export class CommonDbModule {}
